package GUI;
import JDBC.DatabaseConnector;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public final class testUI extends javax.swing.JFrame {

    /**
     * Creates new form testUI
     */
    public testUI() {
        initComponents();
        fetchDataFromDatabase();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
public void fetchDataFromDatabase() {
    
    try{
        // Get a database connection
        Connection con = DatabaseConnector.getConnection();
        
        // Create a statement
        Statement st = con.createStatement();
        
        // Execute the query (replace with your actual table name)
        ResultSet resultSet = st.executeQuery("SELECT * FROM consumers");
        
        while (resultSet.next()) {
                int id = resultSet.getInt("SerialID");
                String fName = resultSet.getString("FirstName");
                String lName = resultSet.getString("LastName");
                System.out.println(fName + " " + lName);               
            }
        
        
        // Get column names from ResultSetMetaData
//        ResultSetMetaData metaData = resultSet.getMetaData();
//        int columnCount = metaData.getColumnCount();
//        String[] columnNames = new String[columnCount];
//        for (int i = 1; i <= columnCount; i++) {
//            columnNames[i - 1] = metaData.getColumnName(i);
//        }
//        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
//
//        // Populate the table model
//        while (resultSet.next()) {
//            Object[] rowData = new Object[columnCount];
//            for (int i = 1; i <= columnCount; i++) {
//                rowData[i - 1] = resultSet.getObject(i);
//            }
//            model.addRow(rowData);
//        }
//
//        // Set the table model to the JTable
//        jTable1.setModel(model);

        
        // Close resources
        resultSet.close();
        st.close();
        DatabaseConnector.closeConnection(con);
        
        
    

    } catch (SQLException | ClassNotFoundException e) {
        e.printStackTrace();
        // Handle exceptions appropriately (e.g., display error message)
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException  ex) {
            java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
