/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author catib
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form UserUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterButton = new javax.swing.JButton();
        DisconnectButton = new javax.swing.JButton();
        ConsumerButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterButton.setBackground(new java.awt.Color(0, 153, 153));
        RegisterButton.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register New Costumer");
        getContentPane().add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 49, 200, -1));

        DisconnectButton.setBackground(new java.awt.Color(0, 153, 153));
        DisconnectButton.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        DisconnectButton.setForeground(new java.awt.Color(255, 255, 255));
        DisconnectButton.setText("For Disconnection");
        DisconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisconnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 180, -1));

        ConsumerButton.setBackground(new java.awt.Color(0, 153, 153));
        ConsumerButton.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        ConsumerButton.setForeground(new java.awt.Color(255, 255, 255));
        ConsumerButton.setText("Comsumers");
        getContentPane().add(ConsumerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 30));

        background.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        background.setText("WATER  BILLING  SYSTEM");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Water Systems Earth Science Presentation in Blue White Illustrated Style (1) (1).jpg"))); // NOI18N
        jLabel1.setText("background");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 950, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisconnectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsumerButton;
    private javax.swing.JButton DisconnectButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
