/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author catib
 */
public class UserUI extends javax.swing.JFrame {

    /**
     * Creates new form UserUI
     */
    public UserUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentButton = new javax.swing.JButton();
        ledgerButton = new javax.swing.JButton();
        WaterMeterButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaymentButton.setBackground(new java.awt.Color(0, 153, 153));
        PaymentButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        PaymentButton.setForeground(new java.awt.Color(255, 255, 255));
        PaymentButton.setText("Payment");
        getContentPane().add(PaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 150, 30));

        ledgerButton.setBackground(new java.awt.Color(0, 153, 153));
        ledgerButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        ledgerButton.setForeground(new java.awt.Color(255, 255, 255));
        ledgerButton.setText("Ledger");
        getContentPane().add(ledgerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 150, 30));

        WaterMeterButton.setBackground(new java.awt.Color(0, 153, 153));
        WaterMeterButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        WaterMeterButton.setForeground(new java.awt.Color(255, 255, 255));
        WaterMeterButton.setText("Water Meter");
        getContentPane().add(WaterMeterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 140, 30));

        background.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        background.setText("WATER  BILLING  SYSTEM");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Water Systems Earth Science Presentation in Blue White Illustrated Style (1) (1).jpg"))); // NOI18N
        jLabel1.setText("background");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 950, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PaymentButton;
    private javax.swing.JButton WaterMeterButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ledgerButton;
    // End of variables declaration//GEN-END:variables
}
